Add setting custom classes and styles to appointments
valincius/BlazorScheduler pull request #66
Opened 2023-06-10 12:37 UTC by Lewan24

- Change appointment text size to a little bit bigger // from 1.2rem to 1.5 rem.
- Modify day height proportionally to text size for good look.
- Add functionallity to set custom classes and styles to appointments // override root style or add classes like bootstrap if needed.
- Add 2 new column to configuration page so user can try setting classes and styles to appointments.

2023-06-10 18:48 UTC, valincius commented
Thanks this looks great. I'll get it merged in later today.

2023-06-11 21:45 UTC, valincius requested changes

2023-06-11 21:45 UTC, valincius commented on BlazorScheduler/Components/Scheduler.razor.cs
> +        [Parameter] public string? RootDayClass { get; set; }
It's hard to tell what the difference is between `RootDaysStyle` and `RootDayStyle`. Could we get some more descriptive names?

2023-06-12 08:31 UTC, Lewan24 commented
Changes done in new commit.

2023-06-12 13:36 UTC, valincius approved these changes

2023-06-12 13:36 UTC, merged